INSERT INTO PROJ VALUES (10,"Product X",20);
INSERT INTO PROJ VALUES (20,"Product Y",20);
INSERT INTO PROJ VALUES (30,"Computerization",60);
INSERT INTO PROJ VALUES (40,"Product Z",80);
INSERT INTO PROJ VALUES (50,"Mobile Apps",60);