ALTER TABLE emp ADD CONSTRAINT emp_pk PRIMARY KEY (empNo);
ALTER TABLE emp ADD CONSTRAINT salary CHECK(salary<12000);
ALTER TABLE emp ADD CONSTRAINT deptNo_Col FOREIGN KEY (deptNo) REFERENCES dept (deptNo);